/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurante.telas;

import Restaurante.controladores.ControladorMesasFechadas;
import Restaurante.controladores.ControladorRestaurante;
import Restaurante.model.MesaTableModel;
import Restaurante.model.ProdutoTableModel;
import core.Entrada;
import javax.swing.JOptionPane;

/**
 *
 * @author LuísFelipe
 */
public class TelaRestaurante extends javax.swing.JFrame
{

    private ControladorRestaurante restaurante;

    /**
     * Creates new form TelaRestaurante
     */
    public TelaRestaurante()
    {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        txtValorCaixa.setEnabled(false);
        setTitle("RESTAURANTE");

        // Inicializar controlador
        restaurante = new ControladorRestaurante();

        // Incializa tabelas
        carregarTabelaProduto();
        carregarTabelaMesas();

        // Se o caixa não estiber aberto, tem que pedir mesas e saldo inicial
        if ( !restaurante.getCaixa().verificarCaixaAberto() )
        {
            abrirCaixa();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtValorCaixa = new javax.swing.JTextField();
        pnlProduto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnAddProduto = new javax.swing.JButton();
        btnAltProduto = new javax.swing.JButton();
        btnDelProduto = new javax.swing.JButton();
        pnlMesas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        btnEditConsumo = new javax.swing.JButton();
        btnCloseMesa = new javax.swing.JButton();
        btnFecharCaixa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Valor em caixa:");

        txtValorCaixa.setBackground(new java.awt.Color(204, 204, 255));
        txtValorCaixa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtValorCaixa.setToolTipText("");

        pnlProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Produtos");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        btnAddProduto.setText("Adicionar produto");
        btnAddProduto.setToolTipText("");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnAltProduto.setText("Editar produto");
        btnAltProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAltProdutoActionPerformed(evt);
            }
        });

        btnDelProduto.setText("Remover produto");
        btnDelProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDelProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAltProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAddProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAltProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelProduto)
                .addContainerGap())
        );

        pnlMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mesas");

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMesas);

        btnEditConsumo.setText("Editar consumo");
        btnEditConsumo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditConsumoActionPerformed(evt);
            }
        });

        btnCloseMesa.setText("Fechar mesa");
        btnCloseMesa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMesasLayout = new javax.swing.GroupLayout(pnlMesas);
        pnlMesas.setLayout(pnlMesasLayout);
        pnlMesasLayout.setHorizontalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(btnEditConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(btnCloseMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMesasLayout.setVerticalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCloseMesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFecharCaixa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFecharCaixa.setText("FECHAR CAIXA");
        btnFecharCaixa.setToolTipText("");
        btnFecharCaixa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFecharCaixaActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar saldos");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorCaixa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFecharCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFecharCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clique no botão "Adicionar Produto".
     *
     * @param evt
     */
    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed

        String descricao = JOptionPane.showInputDialog(null, "Digite uma descrição para o novo produto: ");
        double preco = Entrada.leiaDouble("Digite um preço para o novo produto: ");
        restaurante.novoProduto(descricao, preco);
        carregarTabelaProduto();
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    /**
     * Clique no botão "Editar produto".
     *
     * @param evt
     */
    private void btnAltProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltProdutoActionPerformed

        int idProduto = obterProduto();

        // Se veio zero é porque não tem produtos cadastradoss
        if ( idProduto > 0 )
        {
            String descricao = JOptionPane.showInputDialog(null, "Digite uma nova descrição para o produto (" + restaurante.getListaProdutos().get(0).localizarProduto(idProduto).getDescricao() + "): ");
            double preco = Entrada.leiaDouble("Digite um novo preço para o produto ( " + restaurante.getListaProdutos().get(0).localizarProduto(idProduto).getPreco() + "): ");

            restaurante.salvarProduto(idProduto, descricao, preco);

            carregarTabelaProduto();
        }
    }//GEN-LAST:event_btnAltProdutoActionPerformed

    /**
     * Clique no botão "Remover produto".
     *
     * @param evt
     */
    private void btnDelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdutoActionPerformed

        int idProduto = obterProduto();

        // Se veio zero é porque não tem produtos cadastrados
        if ( idProduto > 0 )
        {
            int confirm = JOptionPane.showConfirmDialog(null, "Tem deseja de que quer excluir o produto " + restaurante.getListaProdutos().get(0).localizarProduto(idProduto).getDescricao() + "?");

            if ( confirm == 0 )
            {
                boolean excluiu = restaurante.getListaProdutos().get(0).removerProduto(idProduto);

                if ( excluiu )
                {
                    JOptionPane.showMessageDialog(null, "Produto excluído");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Este produto está sendo consumido, por tanto não pode ser removido.");
                }

            }

            carregarTabelaProduto();
        }
    }//GEN-LAST:event_btnDelProdutoActionPerformed

    /**
     * Evento ao clicar no botão "Editar consumo".
     *
     * @param evt
     */
    private void btnEditConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConsumoActionPerformed
        TelaConsumo consumo = new TelaConsumo();
        consumo.setRestaurante(restaurante);
        consumo.setMesaId(obterMesa());
        consumo.setVisible(true);
    }//GEN-LAST:event_btnEditConsumoActionPerformed

    /**
     * Evento ao clicar no botão "Fechar mesa".
     *
     * @param evt
     */
    private void btnCloseMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMesaActionPerformed

        // Mesa
        int idMesa = obterMesa();

        // Quantidade de pessoas
        int quantPessoas = Entrada.leiaInt("Digite a quantidade de pessoas da mesa: ");

        // Valor
        double valorMesa = restaurante.getListaMesas().get(0).obterValorDaMesa(idMesa);

        // Mensagem
        String mensagem = "O VALOR TOTAL DA MESA É DE R$ " + valorMesa + "\n"
                + "O VALOR POR PESSOA É DE R$ " + (valorMesa / quantPessoas);

        JOptionPane.showMessageDialog(null, mensagem);

        // Fechar mesa
        restaurante.getListaMesas().get(0).fecharMesa(idMesa);
        restaurante.getCaixa().adicionarValorAoCaixa(valorMesa);
        
        ControladorMesasFechadas mf = new ControladorMesasFechadas();
        mf.adicionarValorDeMesaFechada(idMesa, valorMesa);

        carregarTabelaMesas();
    }//GEN-LAST:event_btnCloseMesaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    /**
     * Carrega tabela de mesas e valor do caixa.
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregarTabelaMesas();
        carregarSaldoCaixa();
    }//GEN-LAST:event_formWindowActivated

    /**
     * Encerra o caixa.
     *
     * @param evt
     */
    private void btnFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCaixaActionPerformed

        // Confirma com o usuário
        int confirm = JOptionPane.showConfirmDialog(null, "Tem deseja de que quer fechar o caixa?");

        if ( confirm == 0 )
        {
            // Verifica se todas as mesas estão fechadas primeiro
            if ( restaurante.getListaMesas().get(0).contarMesasAbertas() > 0 )
            {
                JOptionPane.showMessageDialog(null, "Para poder fechar o caixa é necessário fechar todas as mesas primeiro.");
            }
            else
            {
                RelatorioDeConsumo rt = new RelatorioDeConsumo();
                rt.setVisible(true);
                
                JOptionPane.showMessageDialog(null, "Caixa fechado! Saldo total de R$ " + restaurante.getCaixa().obterSaldoCaixa());
                restaurante.getCaixa().fecharCaixa();
                restaurante.getListaMesas().get(0).apagarTodasAsMesas();
                
                ControladorMesasFechadas cm = new ControladorMesasFechadas();
                cm.apagarRelarorios();
                dispose();
            }
        }
    }//GEN-LAST:event_btnFecharCaixaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        RelatorioDeConsumo rc = new RelatorioDeConsumo();
        rc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals(info.getName()) )
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelaRestaurante().setVisible(true);
            }
        });
    }

    /**
     * Carrega tabela de produtos.
     */
    private void carregarTabelaProduto()
    {
        // Ajustar tabela de protudos
        ProdutoTableModel modeloProduto = new ProdutoTableModel(restaurante.getListaProdutos());
        tblProdutos.setModel(modeloProduto);
    }

    /**
     * Seta dados na tabela de mesas.
     */
    private void carregarTabelaMesas()
    {
        // Ajustar tabela de protudos
        MesaTableModel modeloMesa = new MesaTableModel(restaurante.getListaMesas());
        tblMesas.setModel(modeloMesa);
    }

    /**
     * Seta o valor do saldo em caixa.
     */
    private void carregarSaldoCaixa()
    {
        txtValorCaixa.setText("R$ " + restaurante.getCaixa().obterSaldoCaixa());
    }

    /**
     * Abre caixa.
     */
    private void abrirCaixa()
    {
        // Saldo inicial
        Double initial = Entrada.leiaDouble("Digite um valor para o saldo inicial do caixa:");
        restaurante.getCaixa().definirEstadoInicial(initial);

        // Quantidade de mesas
        int quantMesas = obterValorInteger("Digite qual será a quantidade de mesas disponíveis: ");

        // Criar mesas
        for ( int cont = 0; cont < quantMesas; cont++ )
        {
            restaurante.novaMesa();
        }
        carregarTabelaMesas();
    }

    /**
     * Obter um código de produto válido do usuário.
     */
    private int obterProduto()
    {
        int idProduto = 0;

        if ( restaurante.getListaProdutos().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos um produto primeiro!");
        }
        else
        {
            boolean encontrou = false;

            while ( !encontrou )
            {
                idProduto = obterValorInteger("Digite o código do produto: ");
                encontrou = true;

                if ( restaurante.getListaProdutos().get(0).localizarProduto(idProduto) == null || idProduto < 0 )
                {
                    JOptionPane.showMessageDialog(null, "Este produto não existe! Digite um código válido!");
                    encontrou = false;
                }
            }
        }

        return idProduto;
    }

    /**
     * Obtém um código de mesa válido do usuário.
     *
     * @return
     */
    private int obterMesa()
    {
        boolean encontrou = false;
        int idMesa = 0;

        while ( !encontrou )
        {
            idMesa = obterValorInteger("Digite o código da mesa: ");
            encontrou = true;

            if ( idMesa > restaurante.getListaMesas().size() || idMesa < 1 )
            {
                JOptionPane.showMessageDialog(null, "Este código não existe, digite um válido.");
                encontrou = false;
            }
        }

        return idMesa;
    }

    /**
     * Obtem um valor inteiro do usuário.
     *
     * @param mensagem
     * @return
     */
    private int obterValorInteger( String mensagem )
    {
        int num = 0;
        boolean eInt = false;

        while ( !eInt )
        {
            try
            {
                num = Integer.parseInt(JOptionPane.showInputDialog(null, mensagem));
                eInt = true;
            }
            catch ( NumberFormatException n )
            {
                JOptionPane.showMessageDialog(null, "Digite um número válido!");
            }
        }

        return num;
    }

    /**
     * Obter valor double do usuário.
     *
     * @param mensagem
     * @return
     */
    private double obterValorDouble( String mensagem )
    {
        boolean eDouble = false;
        double num = 0.0;

        while ( !eDouble )
        {
            try
            {
                num = Double.parseDouble(JOptionPane.showInputDialog(null, mensagem));
                eDouble = true;
            }
            catch ( NumberFormatException n )
            {
                JOptionPane.showMessageDialog(null, "Digite um valor válido!");
            }
        }

        return num;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAltProduto;
    private javax.swing.JButton btnCloseMesa;
    private javax.swing.JButton btnDelProduto;
    private javax.swing.JButton btnEditConsumo;
    private javax.swing.JButton btnFecharCaixa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlMesas;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtValorCaixa;
    // End of variables declaration//GEN-END:variables
}
